### ISSUE TITLE
Fix toggle menu for mobile display

### ISSUE THREAD

**Issue by StephanieBr** [hillhacks/hackbeach#2]
Fix bootstrap toggle for mobile screens. Currently sub pages are inaccessible in mobile.

**Comment by mavidser** [comment]
The toggle is there if you scroll to the right. The main title is just too big (and one long word). Can't we just remove [`,Gokarna` ](https://github.com/hillhacks/hackbeach/blob/gh-pages/index.html#L8) from the title to fix this? Seems a bit redundant anyway.

**Comment by PrabhanshuAttri** [comment]
@StephanieBr and @mavidser I have fixed it without shortening the title. The headers were using fixed font size in `px`. I have changed them to `em` which is most preferred.
